### ISSUE TITLE
Possible Error in Calculating Disturbed Storage

### ISSUE THREAD

**Issue by potterzot** [ebimodeling/ghgvcR#11]
Beginning in [ghgvc.R:171](https://github.com/ebimodeling/ghgvcR/blob/master/R/ghgvc.R):

    #calculate D_x
    ...
    FDx[j,g] <- min(j,tR) * (FR[g] - Fx[j,g])
    ...
    Dx[,g] <- rD * (SDx[,g] + FDx[,g])

Eq. 6 of **De Lucia et al 2011** (pg 430) gives `D_x = rD * [SDx - FDx]`, which is notably a subtraction of FDx from SDx rather than the addition in the code above. This would be fine if FDx were calculated in the reverse of the paper's equations, but it isn't (Eq. 8).

**Comment by teixeirak** [comment]
The equation in the paper is correct; this should be (SDx[,g] - FDx[,g]).

**Comment by potterzot** [comment]
Done, thanks.

**Comment by teixeirak** [comment]
Upon closer inspection, I realized that the code was right; the error is in the equation in the paper. The sign conventions here get confusing; I apologize for the error.

Please change the equation back to (SDx[,g] + FDx[,g]).

**Comment by potterzot** [comment]
Done, thanks.
