### ISSUE TITLE
Issues with data-raw/*.csv and R/data.R 

### ISSUE THREAD

**Issue by dlebauer** [ebimodeling/ghgvcR#16]
- [ ] `check()` fails because `Error: 'biome_defaults' is not an exported object from 'namespace:ghgvcr'` 
  - I believe this is because datasets described in R/data.R are in data-raw ?
- [ ] dataset descriptions in data-raw/data.R need to be updated (e.g. description for diamonds dataset is used for biome_defaults dataset)

**Comment by potterzot** [comment]
@dlebauer these are no longer kept in ghgvcR. Can I remove the data description? At this point ghgvcR does not include these data files.

**Comment by dlebauer** [comment]
Yep please remove anything deprecated. Probably worth making pre-R4G tags.

**Comment by potterzot** [comment]
Data descriptions removed.
