### ISSUE TITLE
What is out_test ?

### ISSUE THREAD

**Issue by ValentineHerr** [ebimodeling/ghgvcR#35]
I am working on [this issue](https://github.com/jaydorsey/ghgvcR/issues/1).

In [this file](https://github.com/ebimodeling/ghgvcR/blob/72acee5996c5feff2a50c1a8355f19561cea284f/tests/testthat/test.ghgvc.R#L59), the object "out_test" is called while it has never been defined before.

What is this object? Can find it somewhere or can I recreate it?

**Comment by dlebauer** [comment]
Is it possible that out_test should be one of the out_single and / or out_multi objects? These are created at the beginning of the test file but never used. @potterzot do you have any insight?

**Comment by potterzot** [comment]
I think @dlebauer has that right. If I remember I originally was just testing one, but wanted to test both single-site and multi-sites, and so switched to two different output objects, but must not have switched that line.

**Comment by ValentineHerr** [comment]
Got it!
I am fixing the issue in my branch at [jaydorsey/ghgvcR](https://github.com/jaydorsey/ghgvcR/tree/Valentine).
closing issue here.
