### ISSUE TITLE
test.ghgvcR problem of looking for Tropical_forest where it does not exists

### ISSUE THREAD

**Issue by ValentineHerr** [ebimodeling/ghgvcR#38]
On line 89 of [this test](https://github.com/ebimodeling/ghgvcR/blob/e45b2c591881ea9e74a524c8cc418fa347dc15a8/tests/testthat/test.ghgvc.R#L89) the script is looking for "Tropical_forest" in the site_1, which only contains "BR_Sugarcane" "BR_Soy".

The next couple few lines are assuming Tropical forest exist at site 1 so that also failes.

What was the reasons to test expected values only at site 1?
Should I try to test all sites ?

**Comment by potterzot** [comment]
If I remember right I think this and the previous issue are related in that at the coding weekend I was in the process of trying to rewrite tests for testing more than just the baseline scenario but didn't finish. The old test site.xml data just had "Tropical Forest". Probably this is left over from that. It would be better to test all of them imo.

**Comment by ValentineHerr** [comment]
In fact none of the sites in the multi_site data have tropical forest.

So we could...
EITHER:
- Update the out_multi object to have a slot for each ecosystem present in multi_site ("Temperate_Forest", "Temperate_Cropland", "Temperate_Grassland", 
"Temperate_Pasture", "US_Corn", "Soybean", "Miscanthus", "Switchgrass", 
"BR_Sugarcane", "BR_Soy") --  (or at least one ecosystem per site) 
OR:
- Update multi_site object to have several sites with Tropical forest.

Let me know if you have another idea, you know better than me what the test should do.
And either way, if you want me to work on that, please let me know where/how I can update the data.

**Comment by potterzot** [comment]
> In fact none of the sites in the multi_site data have tropical forest.

That's true, the Tropical forest comes from the original config file (for example, [this one](https://github.com/ebimodeling/ghgvcR/blob/dfd335f02e20aea4b72600578fbc27d2756c2f89/inst/config/config.xml)), which is probably what that test was based on.

My suggestion would be to do some version of the first. The type of ecosystem isn't important, rather that we test at least one non-ag and one ag ecosystem, since they have some differences.

**Comment by ValentineHerr** [comment]
... That makes me realize that the jaydorsay's clone is not up to date for that folder... and I am working off of it on his request.
I'll see with him if he can make a merge from here to his branch. 

I am now closing this issue as it is not relevant anymore.
