### ISSUE TITLE
includeANTH

### ISSUE THREAD

**Issue by potterzot** [ebimodeling/ghgvcR#8]
In [ghgvc.R:26](https://github.com/ebimodeling/ghgvcR/blob/master/R/ghgvc.R), we have:

     26: includeANTH = 1
    ...
    120: if (includeANTH == 0)
    121:   F <- c(ecosystem[['F_CO2']] + ecosystem[['F_anth']], ecosystem[['F_CH4']], ecosystem[['F_N2O']])
    122: else if (includeANTH == 1)
    123:   F <- c(ecosystem[['F_CO2']] + ecosystem[['F_anth']], ecosystem[['F_CH4']], ecosystem[['F_N2O']])

There is no difference between the two calculations in `121` and `123`, and it is hardcoded to 1, so I wonder if there is an error in `121` or `123`?

**Comment by teixeirak** [comment]
Error in 121. Please remove '+ ecosystem[['F_anth']].

Thanks for catching this.

**Comment by potterzot** [comment]
Fixed, thanks for your quick response. One more question on this. `includeANTH` is hard coded to 1 in line 28. Should it be taken from the options in some way instead?

**Comment by teixeirak** [comment]
Yes, it should be included in the options under "Settings"-- see issue #12

**Comment by potterzot** [comment]
Thanks, I'll double check that it takes the value from settings before closing this issue.

**Comment by potterzot** [comment]
Just tidying up. This now defaults to 1, but takes the value from the settings if it is not null.
