### ISSUE TITLE
Logical selection of GHG allows all or one, but should it allow any combination of the 3 GHG?

### ISSUE THREAD

**Issue by potterzot** [ebimodeling/ghgvcR#9]
In [ghgvc.R:32](https://github.com/ebimodeling/ghgvcR/blob/master/R/ghgvc.R), the flow of the assignment means you can only have all 3 GHG (first `if` statement), or only 1 GHG (else it is either 1 of the others). Is this intentional or do we want to make it possible to have any combination of the 3 GHG?

  if (as.logical(options[['co2']]) && as.logical(options[['ch4']]) && as.logical(options[['n2o']])) {
    gf <- 1
    gl <- 3
  } else {
    if (as.logical(options[['co2']]))
      gf <- 1
    else if (as.logical(options[['ch4']]))
      gf <- 2
    else
      gf <- 3

    gl <- gf
  }

**Comment by teixeirak** [comment]
When I wrote the code, there was no need to allow any combination. However, if you can change it easily, I think that would be nice.

**Comment by potterzot** [comment]
Done, thanks
